server:
  port: 8080
spring:
  response:
    success:
      code: 200
      msg: SUCCESS
    exceptions:
      userNotException:
        code: 401
        msg: '사용자 존재하지 않습니다. '
        type: com.ggulling.auth.NotExistsUserException
      userAlreadyExists:
        code: 409
        msg: '사용자가 이미 존재합니다. '
        type: com.ggulling.auth.UserAlreadyExistsException
      FarmUnAvailableException:
        code: 401
        msg: '유효하지 않은 농장입니다. '
        type: com.ggulling.farm.NoFarmAvailableException
      InvalidGgulCountException:
        code: 401
        msg: '현재 보유량보다 많아 유효하지 않습니다. '
        type: com.ggulling.sharing.InvalidGgulCountException
      farmNotExistsException:
        code: 401
        msg: '농가가 존재하지 않습니다. '
        type: com.ggulling.sharing.NotExistsFarmException
