name: "Continuous Integration"

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  quality:
    name: "CI: Check quality"
    working-directory: ./frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Check typescript
        run: npm run type:check

      - name: Check eslint
        run: npm run lint
